# Generated by Django 4.2.7 on 2026-02-04 00:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_file', models.FileField(upload_to='imports/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('records_imported', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('imported_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-lot_number'],
            },
        ),
        migrations.CreateModel(
            name='FixedThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.DecimalField(decimal_places=2, help_text='Orange alert threshold', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('action_level', models.DecimalField(decimal_places=2, help_text='Red action threshold', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bioburden.area')),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='threshold', to='bioburden.lot')),
            ],
            options={
                'verbose_name': 'Fixed Threshold',
                'verbose_name_plural': 'Fixed Thresholds',
                'ordering': ['lot__lot_number'],
            },
        ),
        migrations.CreateModel(
            name='DynamicThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateField(default=django.utils.timezone.now)),
                ('mean_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('std_deviation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sample_count', models.IntegerField()),
                ('dynamic_alert_level', models.DecimalField(decimal_places=2, help_text='Calculated as mean + 2*std', max_digits=10)),
                ('dynamic_action_level', models.DecimalField(decimal_places=2, help_text='Calculated as mean + 3*std', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_thresholds', to='bioburden.area')),
            ],
            options={
                'verbose_name': 'Dynamic Threshold',
                'verbose_name_plural': 'Dynamic Thresholds',
                'ordering': ['-calculation_date', 'area'],
            },
        ),
        migrations.CreateModel(
            name='BioburdenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('sample_id', models.CharField(blank=True, max_length=100, null=True)),
                ('cfu_count', models.DecimalField(decimal_places=2, help_text='Colony Forming Units count', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('dilution_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('adjusted_cfu', models.DecimalField(blank=True, decimal_places=2, help_text='CFU adjusted for dilution', max_digits=10, null=True)),
                ('lab_name', models.CharField(blank=True, max_length=200, null=True)),
                ('analyst', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('alert', 'Alert Level Exceeded'), ('action', 'Action Level Exceeded')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bioburden_tests', to='bioburden.area')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bioburden_tests', to='bioburden.lot')),
            ],
            options={
                'verbose_name': 'Bioburden Test',
                'verbose_name_plural': 'Bioburden Tests',
                'ordering': ['-test_date', 'lot__lot_number'],
                'indexes': [models.Index(fields=['lot', 'test_date'], name='bioburden_b_lot_id_bebb7b_idx'), models.Index(fields=['area', 'test_date'], name='bioburden_b_area_id_fba580_idx'), models.Index(fields=['status'], name='bioburden_b_status_e5b62b_idx')],
            },
        ),
    ]
