# Generated by Django 4.2.7 on 2026-02-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioburden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='primary_organism',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='production_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='secondary_organism',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='tertiary_organism',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
